# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: registry-service.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import service as _service
from google.protobuf import service_reflection
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='registry-service.proto',
  package='',
  syntax='proto3',
  serialized_options=b'\n\031ru.vtb.grpc.mbank.adapterP\001Z\023vtb.ru/afsc/payment\220\001\001',
  serialized_pb=b'\n\x16registry-service.proto\"^\n\x07\x41\x63\x63ount\x12\x0b\n\x03\x62ic\x18\x01 \x01(\t\x12\x0b\n\x03kpp\x18\x02 \x01(\t\x12\x1a\n\x12settlement_account\x18\x03 \x01(\t\x12\x1d\n\x15\x63orrespondent_account\x18\x04 \x01(\t\"_\n\x0e\x41\x63\x63ountRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0b\n\x03inn\x18\x02 \x01(\t\x12\x0b\n\x03kpp\x18\x03 \x01(\t\x12\x0c\n\x04name\x18\x04 \x01(\t\x12\x19\n\x07\x61\x63\x63ount\x18\x05 \x01(\x0b\x32\x08.Account\"j\n\x0c\x41\x63\x63ountReply\x12$\n\x06result\x18\x01 \x01(\x0e\x32\x14.AccountReply.Result\x12\x0f\n\x07message\x18\x02 \x01(\t\"#\n\x06Result\x12\x06\n\x02OK\x10\x00\x12\x11\n\rORG_NOT_FOUND\x10\x01\x32i\n\x08Registry\x12,\n\nGetAccount\x12\x0f.AccountRequest\x1a\r.AccountReply\x12/\n\rDeleteAccount\x12\x0f.AccountRequest\x1a\r.AccountReplyB5\n\x19ru.vtb.grpc.mbank.adapterP\x01Z\x13vtb.ru/afsc/payment\x90\x01\x01\x62\x06proto3'
)



_ACCOUNTREPLY_RESULT = _descriptor.EnumDescriptor(
  name='Result',
  full_name='AccountReply.Result',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='OK', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ORG_NOT_FOUND', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=290,
  serialized_end=325,
)
_sym_db.RegisterEnumDescriptor(_ACCOUNTREPLY_RESULT)


_ACCOUNT = _descriptor.Descriptor(
  name='Account',
  full_name='Account',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='bic', full_name='Account.bic', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='kpp', full_name='Account.kpp', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='settlement_account', full_name='Account.settlement_account', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='correspondent_account', full_name='Account.correspondent_account', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=120,
)


_ACCOUNTREQUEST = _descriptor.Descriptor(
  name='AccountRequest',
  full_name='AccountRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='AccountRequest.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='inn', full_name='AccountRequest.inn', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='kpp', full_name='AccountRequest.kpp', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='AccountRequest.name', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='account', full_name='AccountRequest.account', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=122,
  serialized_end=217,
)


_ACCOUNTREPLY = _descriptor.Descriptor(
  name='AccountReply',
  full_name='AccountReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='AccountReply.result', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message', full_name='AccountReply.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _ACCOUNTREPLY_RESULT,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=219,
  serialized_end=325,
)

_ACCOUNTREQUEST.fields_by_name['account'].message_type = _ACCOUNT
_ACCOUNTREPLY.fields_by_name['result'].enum_type = _ACCOUNTREPLY_RESULT
_ACCOUNTREPLY_RESULT.containing_type = _ACCOUNTREPLY
DESCRIPTOR.message_types_by_name['Account'] = _ACCOUNT
DESCRIPTOR.message_types_by_name['AccountRequest'] = _ACCOUNTREQUEST
DESCRIPTOR.message_types_by_name['AccountReply'] = _ACCOUNTREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Account = _reflection.GeneratedProtocolMessageType('Account', (_message.Message,), {
  'DESCRIPTOR' : _ACCOUNT,
  '__module__' : 'registry_service_pb2'
  # @@protoc_insertion_point(class_scope:Account)
  })
_sym_db.RegisterMessage(Account)

AccountRequest = _reflection.GeneratedProtocolMessageType('AccountRequest', (_message.Message,), {
  'DESCRIPTOR' : _ACCOUNTREQUEST,
  '__module__' : 'registry_service_pb2'
  # @@protoc_insertion_point(class_scope:AccountRequest)
  })
_sym_db.RegisterMessage(AccountRequest)

AccountReply = _reflection.GeneratedProtocolMessageType('AccountReply', (_message.Message,), {
  'DESCRIPTOR' : _ACCOUNTREPLY,
  '__module__' : 'registry_service_pb2'
  # @@protoc_insertion_point(class_scope:AccountReply)
  })
_sym_db.RegisterMessage(AccountReply)


DESCRIPTOR._options = None

_REGISTRY = _descriptor.ServiceDescriptor(
  name='Registry',
  full_name='Registry',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=327,
  serialized_end=432,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetAccount',
    full_name='Registry.GetAccount',
    index=0,
    containing_service=None,
    input_type=_ACCOUNTREQUEST,
    output_type=_ACCOUNTREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='DeleteAccount',
    full_name='Registry.DeleteAccount',
    index=1,
    containing_service=None,
    input_type=_ACCOUNTREQUEST,
    output_type=_ACCOUNTREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_REGISTRY)

DESCRIPTOR.services_by_name['Registry'] = _REGISTRY

Registry = service_reflection.GeneratedServiceType('Registry', (_service.Service,), dict(
  DESCRIPTOR = _REGISTRY,
  __module__ = 'registry_service_pb2'
  ))

Registry_Stub = service_reflection.GeneratedServiceStubType('Registry_Stub', (Registry,), dict(
  DESCRIPTOR = _REGISTRY,
  __module__ = 'registry_service_pb2'
  ))


# @@protoc_insertion_point(module_scope)
